import argparse
from typing import Optional

def parse_arguments():
    parser = argparse.ArgumentParser(
        description="CLI Transcript Analyzer - Analyze transcripts with AI and generate visualizations"
    )
    
    parser.add_argument(
        "transcript_file",
        type=str,
        help="Path to the transcript file to analyze"
    )
    
    parser.add_argument(
        "--min-count",
        type=int,
        default=3,
        help="Minimum word count threshold (default: 3)"
    )
    
    parser.add_argument(
        "--output-format",
        choices=["json", "yaml", "markdown", "text", "html"],
        default="text",
        help="Output format for the analysis (default: text)"
    )
    
    parser.add_argument(
        "--output-file",
        type=str,
        required=False,
        help="Custom output filename (optional, auto-generated by default)"
    )
    
    parser.add_argument(
        "--no-charts",
        action="store_true",
        help="Skip chart generation"
    )
    
    return parser.parse_args()